projekat_django/aplikacija/urls.py
from django.urls import path
from . import views

app_name = 'aplikacija'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.user_register, name='user_register'),
    path('new_movie/', views.new_movie, name='new_movie'),
    path('movies/', views.movies, name='movies'),
    path('movie/<int:id>/', views.movie, name='movie'),
    path('movie/delete/<int:id>/', views.delete_movie, name='delete_movie'),
    path('movie/edit/<int:id>/', views.edit_movie, name='edit_movie'),
    path('movie/<int:id>/comments', views.comments, name='comments'),
    path('movie/<int:id>/new_comment', views.new_comment, name='new_comment')
]

projekat_django/projekat_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('aplikacija.urls'))
]

projekat_django/aplikacija/models.py
from django.db import models
from django.contrib.auth.models import User


class Movie(models.Model):
    name = models.CharField(max_length=70)
    year = models.PositiveSmallIntegerField(default=0)
    synopsis = models.TextField(default='')

    def __str__(self):
        return self.name + '(' + str(self.year) + ')'


class Comment(models.Model):
    content = models.TextField(default='')
    time = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)

    def __str__(self):
        return str(self.user) + ' - ' + str(self.movie)

projekat_django/aplikacija/forms.py
from django.forms import ModelForm
from .models import Movie, Comment
from django import forms

class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'year', 'synopsis']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

projekat_django/aplikacija/views.py
from django.contrib.auth import login
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse

from .forms import CommentForm, MovieForm, RegisterForm
from .models import Movie
from .models import Comment
from django.contrib.auth.models import User
# Create your views here.


def index(req):
    if not req.user.is_authenticated:
        return render(req, 'index.html', {'page_title': 'Movie reviews'})
    else:
        return redirect('aplikacija:movies')


@login_required
def movies(req):
    tmp = Movie.objects.all()
    return render(req, 'movies.html', {'movies': tmp})


@login_required
def movie(req, id):
    tmp = get_object_or_404(Movie, id=id)
    return render(req, 'movie.html', {'movie': tmp, 'page_title': tmp.name})


@login_required
def comments(req, id):
    tmp = Comment.objects.filter(movie=id)
    m = Movie.objects.get(id=id)
    return render(req, 'comments.html', {'comments': tmp, 'movie': m})


@login_required
def new_comment(req, id):
    if req.method == 'POST':
        form = CommentForm(req.POST)
        if form.is_valid():
            m = Movie.objects.get(id=id)
            c = Comment(content=form.cleaned_data['content'], user=req.user, movie=m)
            c.save()
            return redirect('aplikacija:comments', id)
        else:
            return render(req, 'newComment.html', {'form': form, 'id': id})
    else:
        form = CommentForm()
        return render(req, 'newComment.html', {'form': form, 'id': id})


@permission_required('aplikacija.add_movie')
def new_movie(req):
    if req.method == 'POST':
        form = MovieForm(req.POST)

        if form.is_valid():
            m = Movie(name=form.cleaned_data['name'], year=form.cleaned_data['year'], synopsis=form.cleaned_data['synopsis'])
            m.save()
            return redirect('aplikacija:movies')
        else:
            return render(req, 'newMovie.html', {'form': form})
    else:
        form = MovieForm()
        return render(req, 'newMovie.html', {'form': form})


@permission_required('aplikacija.change_movie')
def edit_movie(req, id):
    if req.method == 'POST':
        form = MovieForm(req.POST)

        if form.is_valid():
            m = Movie.objects.get(id=id)
            m.name = form.cleaned_data['name']
            m.year = form.cleaned_data['year']
            m.synopsis = form.cleaned_data['synopsis']
            m.save()
            return redirect('aplikacija:movies')
        else:
            return render(req, 'editMovie.html', {'form': form, 'id': id})
    else:
        m = Movie.objects.get(id=id)
        form = MovieForm(instance=m)
        return render(req, 'editMovie.html', {'form': form, 'id': id})


@permission_required('aplikacija.delete_movie')
def delete_movie(req, id):
    to_delete = get_object_or_404(Movie, id=id)
    to_delete.delete()
    return redirect('aplikacija:movies')


def user_register(req):
    if req.method == 'POST':
        form = RegisterForm(req.POST)


        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(req, 'register.html', {
                    'form': form,
                    'error_message': 'Username already exists.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(req, 'register.html', {
                    'form': form,
                    'error_message': 'Email already exists.'
                })

            user = User.objects.create_user(
                form.cleaned_data['username'],
                form.cleaned_data['email'],
                form.cleaned_data['password'],
            )

            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']

            user.save()
            login(req, user)

            return redirect('aplikacija:movies')
        else:
            return render(req, 'register.html', {
                'form': form,
                'error_message': 'Error'
            })
    else:
        form = RegisterForm()
        return render(req, 'register.html', {'form': form})

projekat_django/aplikacija/templates/comments.html
{%  extends 'master.html' %}

{% block title %}
    Comments for {{ movie.name }}({{ movie.year }})
{% endblock %}

{%  block content %}

<div>
    <h1>{{ movie.name }}({{ movie.year }})
        <a href="{% url 'aplikacija:new_comment' movie.id %}">
            <span class="badge badge-dark">Add comment</span>
        </a>
        <a href="{% url 'aplikacija:movie' movie.id %}">
            <span class="badge badge-dark">Cancel</span>
        </a>
    </h1>

</div>

{% if not comments %}
    <div>
        <h1>
            No comments for this movie
        </h1>
    </div>
{% else %}
    {% for comment in comments %}
    <div class="card">
      <div class="card-header" style="text-align:left">
        {{ comment.user }}
      </div>
      <div class="card-body">
        <p class="card-text" style="text-align:left">{{ comment.content }}</p>
      </div>
      <div class="card-footer text-muted" style="text-align:right">
          {{ comment.time }}
      </div>
    </div>
    <br/>
    {% endfor %}
{% endif %}
{% endblock %}

projekat_django/aplikacija/templates/editMovie.html
{% extends 'master.html' %}

{% block title %}
    Edit movie
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'aplikacija:edit_movie' id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.name.id_for_label }}" name="{{ form.name.name }}" value="{{ form.name.value }}">
            {% if form.name.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.name.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.year.id_for_label }}">{{ form.year.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.year.id_for_label }}" name="{{ form.year.name }}" value="{{ form.year.value }}">
            {% if form.year.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.year.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.synopsis.id_for_label }}">{{ form.synopsis.label_tag }}</label>
            <textarea class="form-control" id="{{ form.synopsis.id_for_label }}" name="{{ form.synopsis.name }}" rows="5">{{ form.synopsis.value }}</textarea>
            {% if form.synopsis.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.synopsis.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Save"/>
    </form>

{% endblock %}

projekat_django/aplikacija/templates/index.html
{%  extends 'master.html' %}

{%  block content %}
    <p>You are not logged in.</p>
    <a href="{% url 'login'%}">Click here to login.</a>
    <a href="{% url 'aplikacija:user_register'%}">Click here to sign up.</a>
{% endblock %}

projekat_django/aplikacija/templates/movie.html
{% extends 'master.html' %}

{% block content %}

    <div class="card">
        <div class="card-header">
            <h1>
                {{ movie.name }}({{ movie.year }})
                {% if perms.aplikacija.change_movie %}
                    <a href="{% url 'aplikacija:edit_movie' movie.id %}">
                        <span class="badge badge-dark">Edit</span>
                    </a>
                {% endif %}
                {% if perms.aplikacija.delete_movie %}
                    <a href="{% url 'aplikacija:delete_movie' movie.id %}">
                        <span class="badge badge-dark">Delete</span>
                    </a>
                {% endif %}
                    <a href="{% url 'aplikacija:comments' movie.id %}">
                        <span class="badge badge-dark">See comments</span>
                    </a>
            </h1>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>{{ movie.synopsis }}</p>
            </blockquote>
        </div>
    </div>

{% endblock %}

projekat_django/aplikacija/templates/movies.html
{%  extends 'master.html' %}

{% block title %}
    Movies
{% endblock %}

{%  block content %}
    {% if not movies %}
    <div>
        <h1>
            Movie list is empty
        </h1>
    </div>
    {% else %}
    <div>
        <h1>
            Movie list:
        </h1>
    </div>
    <div class="list-group">
        {% for movie in movies %}
            <a class="list-group-item list-group-item-action" href="{% url 'aplikacija:movie' movie.id %}">
                {{ movie.name }} ({{ movie.year}})
            </a>

        {% endfor %}
    </div>
    {% endif %}
{% endblock %}

projekat_django/aplikacija/templates/newComment.html
{% extends 'master.html' %}

{% block title %}
    New Comment
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'aplikacija:new_comment' id %}">
    {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.content.id_for_label }}">{{ form.content.label_tag }}</label>
            <textarea class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.name }}" rows="5"></textarea>
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Add"/>

    </form>

{% endblock %}

projekat_django/aplikacija/templates/newMovie.html
{% extends 'master.html' %}

{% block title %}
    New movie
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'aplikacija:new_movie' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.name.id_for_label }}" name="{{ form.name.name }}">
            {% if form.name.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.name.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.year.id_for_label }}">{{ form.year.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.year.id_for_label }}" name="{{ form.year.name }}">
            {% if form.year.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.year.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.synopsis.id_for_label }}">{{ form.synopsis.label_tag }}</label>
            <textarea class="form-control" id="{{ form.synopsis.id_for_label }}" name="{{ form.synopsis.name }}" rows="5"></textarea>
            {% if form.synopsis.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.synopsis.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Add"/>
    </form>

{% endblock %}

projekat_django/aplikacija/templates/register.html
{% extends 'master.html' %}

{% block title %}
    Register user
{% endblock %}

{% block content %}

<div>
    <h1>
        Register new user
    </h1>
</div>

<form method="post" action="{% url 'aplikacija:user_register' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.username.id_for_label }}">Enter username</label>
        <input type="text" class="form-control" id="{{ form.username.id_for_label }}" name="{{ form.username.name }}" placeholder="Username">
    </div>
    <div class="form-group">
        <label for="{{ form.email.id_for_label }}">Enter email</label>
        <input type="email" class="form-control" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" aria-describedby="emailHelp" placeholder="Email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="{{ form.password.id_for_label }}">Enter password</label>
        <input type="password" class="form-control" id="{{ form.password.id_for_label }}" name="{{ form.password.name }}" placeholder="Password">
    </div>
    <div class="form-group">
        <label for="{{ form.first_name.id_for_label }}">Enter first name</label>
        <input type="text" class="form-control" id="{{ form.first_name.id_for_label }}" name="{{ form.first_name.name }}" placeholder="First name">
    </div>
    <div class="form-group">
        <label for="{{ form.last_name.id_for_label }}">Enter last name</label>
        <input type="text" class="form-control" id="{{ form.last_name.id_for_label }}" name="{{ form.last_name.name }}" placeholder="Last name">
    </div>
    {% if error_message %}
        <p class="bg-danger p-d ml-b">{{ error_message }}</p>
    {% endif %}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

projekat_django/templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'aplikacija:movies' %}">
        <img src="{% static 'img/film.png' %}" width="30" height="30" class="d-inline-block align-top" alt="logo"/>
        Movie Reviews
    </a>

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            {% if not perms.aplikacija.add_movie %}
                <a class="nav-link disabled" href="{% url 'aplikacija:new_movie' %}">New movie</a>
            {% else %}
                <a class="nav-link" href="{% url 'aplikacija:new_movie' %}">New movie</a>
            {% endif %}
        </li>
    </ul>

    {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout {{ user.get_username }}</a>
    {% endif %}
</nav>

projekat_django/templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>
        {% block title %}
            {{ page_title|default:"Untitled Page" }}
        {% endblock title %}
    </title>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
</head>

<body>

    {% include 'header.html' %}

    <div class="container" style="text-align: center; margin-top: 50px">
        {% block content %}
            <p>Placeholder text in base template. Replace with page content.</p>
        {% endblock content %}
    </div>

</body>
</html>